#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)


def generate_random_password(length):
    # Generate random bytes and convert them to a hexadecimal string
    random_bytes = os.urandom(length)
    password = random_bytes.hex()
    return password[:length]


# this values must exists in the json stdin
# agent.set_env("MAIL_SERVER", data["mail_server"])

# DB Config
POSTGRES_DB = data.get("POSTGRES_DB", "joplin")
POSTGRES_USER = data.get("POSTGRES_USER", "joplin")
POSTGRES_PASSWORD = generate_random_password(16)

db_config = {
    "POSTGRES_ROOT_HOST": "joplin-pgsql",
    "POSTGRES_DATABASE": POSTGRES_DB,
    "POSTGRES_USER": POSTGRES_USER,
    "POSTGRES_PASSWORD": POSTGRES_PASSWORD,
}
agent.write_envfile("database.env", db_config)

joplin_db_config = {
    "JOPLIN_DBENGINE": "postgresql",
    "JOPLIN_DBHOST": "joplin-pgsql",
    "JOPLIN_DBNAME": POSTGRES_DB,
    "JOPLIN_DBUSER": POSTGRES_USER,
    "JOPLIN_DBPASS": POSTGRES_PASSWORD,
}
agent.write_envfile("joplin-db.env", joplin_db_config)

agent.dump_env()
