#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent
import os

request = json.load(sys.stdin)
renv = request["environment"]


def str_to_bool(s):
    return s.lower() in ("true", "1", "yes")


configure_retval = agent.tasks.run(
    agent_id=os.environ["AGENT_ID"],
    action="configure-module",
    data={
        "lets_encrypt": str_to_bool(renv["TRAEFIK_LETS_ENCRYPT"]),
        "host": renv["TRAEFIK_HOST"],
        "http2https": str_to_bool(renv["TRAEFIK_HTTP2HTTPS"]),
    },
)
agent.assert_exp(
    configure_retval["exit_code"] == 0, "The configure-module subtask failed!"
)
